owner: DieSchoeneWolke # Your GitHub organization or username, where this repository lives
repo: dieschoenewolke-upptime  # The name of this repository

sites:
  - name: DieSchoeneWolke
    url: https://dieschoenewolke.com
  - name: DieSchoeneWolke Mail
    url: https://mail.dieschoenewolke.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: dieschoenewolke.github.io
  #baseUrl: /dieschoenewolke-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DieSchoeneWolke Status
  introTitle: 
  introMessage: Dies ist die Statusseite für [**DieSchoeneWolke**](https://dieschoenewolke.com) von unserem [GitHub repository](https://github.com/DieSchoeneWolke/dieschoenewolke-upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Kontakt
      href: mailto://kontakt@mail.dieschoenewolke.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

user-agent: DieSchoeneWolke

i18n:
  footer: "[**Upptime**](https://upptime.js.org/) ist der Open-Source-Update-Monitor und die Statusseite, die vollständig von GitHub angetrieben wird."
